<a href="https://colab.research.google.com/github/kitagawaowo/Colabs/blob/main/Week3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [59]:
#@title GPT Reinas
def es_factible(tablero, fila, columna, n):
    # Verifica si la reina puede ser colocada en la posición dada
    # sin conflictos con las demás reinas
    for i in range(fila):
        if tablero[i] == columna or \
           tablero[i] - i == columna - fila or \
           tablero[i] + i == columna + fila:
            return False
    return True

def n_reinas(tablero, fila, n):
    # Caso base: todas las reinas han sido colocadas
    if fila == n:
        return True

    # Coloca la reina en la fila actual, columna por columna
    for columna in range(n):
        if es_factible(tablero, fila, columna, n):
            tablero[fila] = columna
            # Llamada recursiva para colocar la siguiente reina
            if n_reinas(tablero, fila+1, n):
                return True
    # Si no se encuentra solución, se retrocede y se prueba otra posición
    return False

# Función principal para resolver el problema de las n reinas
def resolver_n_reinas(n):
    tablero = [-1] * n
    if not n_reinas(tablero, 0, n):
        print("No se encontró solución.")
    else:
        print("Solución:")
        for i in range(n):
            fila = ["-"] * n
            fila[tablero[i]] = "Q"
            print("".join(fila))

resolver_n_reinas(4)

Solución:
-Q--
---Q
Q---
--Q-


In [60]:
#@title GPT Binaria
def busqueda_binaria(arr, inicio, fin, x):
    # Caso base: si el inicio es mayor que el final, el elemento no está en el arreglo
    if inicio > fin:
        return -1

    # Encuentra el punto medio del arreglo
    medio = (inicio + fin) // 2

    # Si el elemento está en la mitad del arreglo, devuelve el índice
    if arr[medio] == x:
        return medio

    # Si el elemento es menor que el elemento en la mitad del arreglo,
    # busca en la mitad izquierda
    elif arr[medio] > x:
        return busqueda_binaria(arr, inicio, medio-1, x)

    # Si el elemento es mayor que el elemento en la mitad del arreglo,
    # busca en la mitad derecha
    else:
        return busqueda_binaria(arr, medio+1, fin, x)

# Función principal para realizar la búsqueda binaria en un arreglo dado
def busqueda(arr, x):
    return busqueda_binaria(arr, 0, len(arr)-1, x)


In [61]:
#@title Funcion maximo y minimo
import random as r

def mayor(a, b):
    return a if a > b else b

def menor(a, b):
    return a if a < b else b

def divAndVenc(a, i, j, func):
    if i == j:
        return a[i]
    else:
        med = (i + j) // 2
        maxi = divAndVenc(a, i, med, func)
        maxd = divAndVenc(a, med + 1, j, func)

        return func(maxi, maxd)
    
arr = [r.randint(100, 500) for _ in range(20)]


print(arr)
print(divAndVenc(arr, 0, len(arr) - 1, mayor))
print(divAndVenc(arr, 0, len(arr) - 1, menor))

arr.sort()
print(arr)


[444, 167, 495, 355, 174, 388, 327, 474, 162, 269, 160, 291, 232, 276, 168, 467, 202, 312, 404, 159]
495
159
[159, 160, 162, 167, 168, 174, 202, 232, 269, 276, 291, 312, 327, 355, 388, 404, 444, 467, 474, 495]


In [62]:
#@title Multiplicar usando divide y venceras
def multiplicar(a, b, n):
    if n == 1:
        return a * b
    else:
        a_str = str(a)
        b_str = str(b)
        n2 = n // 2
        ai = int(a_str[:-n2]) or 0
        ad = int(a_str[-n2:]) or 0
        bi = int(b_str[:-n2]) or 0
        bd = int(b_str[-n2:]) or 0
        z1 = multiplicar(ai, bi, n2) * 10**n
        z2 = (multiplicar(ai, bd, n2) + multiplicar(ad, bi, n2)) * 10**(n2) or 0
        z3 = multiplicar(ad, bd, n2) or 0
        return z1 + z2 + z3

a = 1234
b = 3127
n = max(len(str(a)), len(str(b)))

resultado = multiplicar(a, b, n)

print(resultado)
print(a * b)

3858718
3858718


In [63]:
#@title GPT Karatsuba
def karatsuba(a, b):
    # Convertir los números a string para contar los dígitos
    a_str = str(a)
    b_str = str(b)
    
    # Determinar la cantidad de dígitos
    n = max(len(a_str), len(b_str))
    
    # Caso base para la recursión
    if n == 1:
        return a * b
    
    # Dividir los números en dos partes iguales
    n2 = n // 2
    a1 = int(a_str[:-n2] or '0')
    a0 = int(a_str[-n2:] or '0')
    b1 = int(b_str[:-n2] or '0')
    b0 = int(b_str[-n2:] or '0')
    
    # Calcular las tres multiplicaciones recursivamente
    ac = karatsuba(a1, b1)
    bd = karatsuba(a0, b0)
    adbc = karatsuba(a1 + a0, b1 + b0) - ac - bd
    
    # Calcular el resultado final
    return (10 ** (2 * n2)) * ac + (10 ** n2) * adbc + bd

# Ejemplo de uso
a = 123456789
b = 987654321
a = 11
b = 5
resultado = karatsuba(a, b)
print(resultado) # Salida: 12193263113702179569


55


### V o F la llamada recursiva utilizando la tecnica recursiva de divide o venceras pertenece al paso de combinar -> F

In [68]:
#@title Multiplicación de matrices
import numpy as np
def matrix_multiplication(matrix1, matrix2):
    """
    Multiplicación de matrices utilizando divide y vencerás.
    """
    n = len(matrix1)
    if n == 1:
        return np.array([[matrix1[0][0] * matrix2[0][0]]])
    else:
        # Dividir las matrices en 4 partes iguales
        a11, a12, a21, a22 = partition(matrix1)
        b11, b12, b21, b22 = partition(matrix2)
        
        # Realizar los cálculos de manera recursiva
        p1 = matrix_multiplication(a11, b11) + matrix_multiplication(a12, b21)
        p2 = matrix_multiplication(a11, b12) + matrix_multiplication(a12, b22)
        p3 = matrix_multiplication(a21, b11) + matrix_multiplication(a22, b21)
        p4 = matrix_multiplication(a21, b12) + matrix_multiplication(a22, b22)
        
        # Unir las cuatro partes en una única matriz
        result = np.zeros((n, n))
        result[:n//2, :n//2] = p1
        result[:n//2, n//2:] = p2
        result[n//2:, :n//2] = p3
        result[n//2:, n//2:] = p4
        
        return result
        
def partition(matrix):
    """
    Particiona una matriz en 4 partes iguales.
    """
    n = len(matrix)
    if n % 2 == 0:
        half = n//2
        a11 = matrix[:half, :half]
        a12 = matrix[:half, half:]
        a21 = matrix[half:, :half]
        a22 = matrix[half:, half:]
        return a11, a12, a21, a22
    else:
        raise ValueError("La matriz debe tener dimensiones pares")
        
# Ejemplo de uso
#a = np.array([[1, 2, 4, 5], [3, 4, 3, 1], [3, 4, 1, 7], [3, 4, 5, 8]])
#b = np.array([[5, 6, 7, 9], [7, 8, 9, 10], [3, 4, 9, 1], [3, 4, 4, 6]])
#A = np.array([[1, 2], [3, 4]])
#B = np.array([[5, 6], [7, 8]])

A = np.random.randint(10, size=(4, 4))
B = np.random.randint(10, size=(4, 4))

print(matrix_multiplication(A, B))

C = np.dot(A, B)
print()
print(C)


[[27. 42. 36. 49.]
 [29. 86. 91. 32.]
 [44. 97. 93. 29.]
 [34. 72. 80. 54.]]

[[27 42 36 49]
 [29 86 91 32]
 [44 97 93 29]
 [34 72 80 54]]


In [85]:
# Multiplicar a y c.  El resultado guardarlo en c.  Los parametros i y j parten de 0.  Los parametros ii y jj inician con la logitud de la matriz a - 1
def matmul(a, b, c, i, ii, j, jj):
  if i == ii:
    temp = 0
    for k in range(len(a)):
      temp += a[i][k] * b[k][j]
    c[i][j] = temp
  else:
    # (1) Dividir en subproblemas
    imid = (i + ii) // 2
    jmid = (j + jj) // 2
    # (2) Conquistar significa las llamadas recursivas
    matmul(a, b, c,        i, imid,        j, jmid)
    matmul(a, b, c, imid + 1,   ii,        j, jmid)
    matmul(a, b, c,        i, imid, jmid + 1, jj)
    matmul(a, b, c, imid + 1,   ii, jmid + 1, jj)

In [83]:
# Creamos dos vectores con numeros aleatorios (entre 0 y 10)
# el vector a con 3 filas y 4 columnas
# el vector b con 4 filas y 2 columnas
a = np.random.randint(10, size=(4, 4))
b = np.random.randint(10, size=(4, 4))


In [84]:
#Obtenemos en la matriz c la multiplicacion de las matrices a y b
#Para que usamos assert? shorturl.at/fgKV9

c = np.zeros((4, 4))
matmul(a, b, c, 0, len(a) - 1, 0, len(b) - 1)
assert (c == np.matmul(a, b)).all()
print(c)

[[139. 103. 134. 121.]
 [159. 114. 162.  87.]
 [115.  82. 111.  83.]
 [118. 112. 111. 110.]]
